deployment:
  name: tetris
  replicaCount: 1
image:
  repository: 061039788053.dkr.ecr.us-east-2.amazonaws.com/tom
  tag: 1
  containerPort: 8080
service:
  type: ClusterIP
  clusterIPPort: 8080
resource:
  cpu:
    requests: 0.1
    limit: 0.2
  memory:
    requests: 200Mi
    limit: 300Mi
environment:
  env: DEV
namespace: dev
